[connection]
network = "Local"
[connection.node.mainnet]
ip_address = "0.0.0.0"
sse_port=9999
[connection.node.testnet]
ip_address="0.0.0.0"
sse_port=9999
[connection.node.local]
ip_address="127.0.0.1"
sse_port=9998

[storage]
db_path = "./target/test_storage"
sse_cache = "./target/test_storage"

[rest_server]
port = 17777

[sse_server]
port = 19999
