[[connections]]
ip_address = "127.0.0.1"
sse_port = 9999
rest_port = 8888
max_retries = 10
delay_between_retries_in_seconds = 5
allow_partial_connection = false
enable_logging = true

[storage]
storage_path = "/var/lib/casper-event-sidecar"

[storage.sqlite_config]
file_name = "sqlite_database.db3"
max_connections_in_pool = 100
# https://www.sqlite.org/compile.html#default_wal_autocheckpoint
wal_autocheckpointing_interval = 1000

[rest_server]
port = 18888
max_concurrent_requests = 50
max_requests_per_second = 50

[event_stream_server]
port = 19999
max_concurrent_subscribers = 100
event_stream_buffer_length = 5000