[rpc_server.main_server]
enable_server = true
ip_address = "0.0.0.0"
port = 7777
qps_limit = 100
max_body_bytes = 2621440
cors_origin = ""

[rpc_server.speculative_exec_server]
enable_server = true
ip_address = "0.0.0.0"
port = 7778
qps_limit = 1
max_body_bytes = 2621440
cors_origin = ""

[rpc_server.node_client]
ip_address = "3.20.57.210"
port = 7777
max_message_size_bytes = 4194304
message_timeout_secs = 10
client_access_timeout_secs = 10
keepalive_timeout_ms = 4_000

[rpc_server.node_client.exponential_backoff]
initial_delay_ms = 1000
max_delay_ms = 32000
coefficient = 2
max_attempts = 30

[sse_server]
enable_server = true
disable_event_persistence = false

[[sse_server.connections]]
ip_address = "168.254.51.1"
sse_port = 9999
rest_port = 8888
max_attempts = 100
delay_between_retries_in_seconds = 10
allow_partial_connection = true
enable_logging = false
no_message_timeout_in_seconds = 20
sleep_between_keep_alive_checks_in_seconds = 10

[[sse_server.connections]]
ip_address = "168.254.51.2"
sse_port = 9999
rest_port = 8888
max_attempts = 100
delay_between_retries_in_seconds = 10
allow_partial_connection = false
enable_logging = false
no_message_timeout_in_seconds = 20
sleep_between_keep_alive_checks_in_seconds = 10

[[sse_server.connections]]
ip_address = "168.254.51.3"
sse_port = 9999
rest_port = 8888
max_attempts = 100
delay_between_retries_in_seconds = 10
allow_partial_connection = false
enable_logging = false
no_message_timeout_in_seconds = 20
sleep_between_keep_alive_checks_in_seconds = 10

[sse_server.event_stream_server]
port = 19999
max_concurrent_subscribers = 100
event_stream_buffer_length = 5000

[storage]
storage_folder = "/var/lib/casper-sidecar"

[storage.sqlite_config]
enabled = true
file_name = "sqlite_database.db3"
max_connections_in_pool = 100
# https://www.sqlite.org/compile.html#default_wal_autocheckpoint
wal_autocheckpointing_interval = 1000

[rest_api_server]
enable_server = true
port = 18888
max_concurrent_requests = 50
max_requests_per_second = 50

[admin_api_server]
enable_server = true
port = 18887
max_concurrent_requests = 1
max_requests_per_second = 1
